Repository CertifaiAI/cdle-traininglabs, pull requests merged in 2020-10, with the labels that each got.

#106 Fixed old package import
  dl4j-cv-labs/src/main/java/ai/certifai/training/facial_recognition/FaceRecognitionWebcam.java
  dl4j-cv-labs/src/main/java/ai/certifai/training/image_processing/Quantization.java
Labels: bug

#107 Delete Food Classification example
  dl4j-cv-labs/src/main/java/ai/certifai/solution/classification/FoodClassification.java
  dl4j-cv-labs/src/main/java/ai/certifai/solution/classification/FoodDataSetIterator.java
Labels: bug, invalid

#111 [WIP] update README.md
  README.md
Labels: enhancement

#115 added ffmpeg maven dependencies to solve ffmpegframegrabber issue
  dl4j-cv-labs/pom.xml
  pom.xml
Labels: bug, critical

#117 change to certifai.ai
  dl4j-spark-labs/src/main/java/ai/certifai/HelloWorldSpark.java
Labels: invalid

#125 add license, author, description
  dl4j-labs/src/main/java/ai/certifai/solution/classification/Multiclass.java
  dl4j-labs/src/main/java/ai/certifai/training/classification/Multiclass.java
  dl4j-spark-labs/src/main/java/ai/certifai/HelloWorldSpark.java
Labels: enhancement
